module.exports = {
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    // config.yml is generated by setup.sh (from config.yml.template) and gitignored,
    // so it won't exist in a fresh checkout or CI. Tests use the template instead.
    '^@config$': '<rootDir>/config.yml.template'
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  testMatch: ['**/__tests__/**/*.test.js'],
  transform: {
    '^.+\\.(js|jsx)$': 'babel-jest',  // Changed this line from babel-loader to babel-jest
    '\\.ya?ml(\\.template)?$': '<rootDir>/jest.yamlTransform.js'
  },
  collectCoverageFrom: [
    "src/**/*.{js,jsx}",
    "!src/index.js",
    "!**/node_modules/**",
  ],
};
