#!/usr/bin/env python
import subprocess
import json
import os
import argparse 

CLUSTER_NAME="Terra"

def main():
    # create parser object 
    parser = argparse.ArgumentParser(description = "Accounting utility wrapper for " + CLUSTER_NAME) 

    # defining arguments for parser object 
    parser.add_argument("-l", "--list", action='store_true',
                        help = "List all allocations for current user.")

    # defining arguments for parser object 
    parser.add_argument("-d", "--default", nargs = 1, 
                        type = str, metavar = "account_no", default = None, 
                        help = "Switch the default project account to the given account no.")

     # parse the arguments from standard input 
    args = parser.parse_args() 

    # calling functions depending on type of argument 
    if args.list == True: 
        print('{ "data": [{"used_pending_su": 0.0, "account": "122809601331", "pi": "Liu, Honggao", "default": "N", "fy": "2020", "allocation": 10.0, "balance": 10.0}, {"used_pending_su": -49.53, "account": "122809608377", "pi": "Liu, Honggao", "default": "Y", "fy": "2020", "allocation": 5000.0, "balance": 4950.47}]}')
        exit(0)
    elif args.default != None: 
        print("Success")
        exit(0)
        # switch_default_account(args) 
    else:
        parser.print_help()

if __name__ == "__main__": 
    main()