#!/usr/bin/env python
import subprocess
import json
import os
import argparse 

CLUSTER_NAME="Terra"

def main():
    # create parser object 
    parser = argparse.ArgumentParser(description = "Job utility wrapper for " + CLUSTER_NAME) 

    # defining arguments for parser object 
    parser.add_argument("-l", "--list", action='store_true',
                        help = "List all jobs for current user.")

    
    parser.add_argument("-k", "--kill", nargs = 1, 
                        type = str, metavar = "job_id", default = None, 
                        help = "Kill a job with the given job id.")

    parser.add_argument("-o", "--output", nargs = 2, 
                        type = str, metavar=('job_id', 'n_lines'), default = None, 
                        help = "Output the last n_lines of output of a given job_id")

     # parse the arguments from standard input 
    args = parser.parse_args() 

    # calling functions depending on type of argument 
    if args.list == True: 
        print('{ "data": []}')
        exit(0)
    elif args.kill != None: 
        print("Success")
        exit(0)
    elif args.output != None:
        print("Success")
        exit(0)
    else:
        parser.print_help()

if __name__ == "__main__": 
    # calling the main function 
    main()