#!/usr/bin/env python

print('{ "data": [{"name": "/home ", "disk_usage": 105856, "disk_limit": 10485760, "file_usage": 507, "file_limit": 10000}, {"name": "/scratch ", "disk_usage": 1556864, "disk_limit": 1073741824, "file_usage": 20779, "file_limit": 250000}]}')