#!/usr/bin/python

import subprocess
import json

class Allocation:
    def __init__(self, account, fy, default, allocation, used_pending_su, balance, pi):
        self.account = account
        self.fy = fy
        self.default = default
        self.allocation = float(allocation)
        self.used_pending_su = float(used_pending_su)
        self.balance = float(balance)
        self.pi = pi

def alloc_from_list(data):
    return Allocation(data[0], data[1], data[2], data[3], data[4], data[5], data[6])

output=subprocess.check_output(["myproject", "-l"])
output = output.split('\n')
output = output[5:] # skip the headers

allocations = []
for line in output:
    if '|' in line:
        line = line.strip('|')
        data = line.split('|')
        data = map(lambda x: x.strip(), data)
        allocation = alloc_from_list(data)
        allocations.append(allocation)
    
json_data = json.dumps([ob.__dict__ for ob in allocations])
print('{ "data": ' + json_data + '}')