#!/bin/python3
import json
import re
import argparse
import ast

def replace_flag(match, flag_dict):
    flagchar, flagname = match.group(1), match.group(2)
    if flagname in flag_dict:
        return f"-{flagchar} {flag_dict[flagname]}"
    else:
        return ""

def replace_no_flag(match, flag_dict):
    flagname = match.group(1)
    if flagname in flag_dict:
        return flag_dict[flagname]
    else:
        return ""

class Engine():
    def __init__(self):
        self.enviroment = None
        self.schema = None
        self.map = None
        self.script = None
    
    def set_schema(self, schema_path):
        with open(schema_path) as json_file:
            self.schema = json.load(json_file)

    def set_map(self, map_path):
        with open(map_path) as json_file:
            self.map = json.load(json_file)

    def get_enviroment(self):
        return self.enviroment

    def get_schema(self):
        return self.schema
    
    def get_map(self):
        return self.map
    
    def fetch_template(self, template_path):
        with open(template_path) as text_file:
            template = text_file.read()
            return template
        
    def set_enviroment(self, enviroment):
        self.enviroment = enviroment
        self.set_map("maps/" + enviroment + ".json")
        self.set_schema("schemas/" + enviroment + ".json")
    
    def custom_replace(self, template, map, params):
        # 2 Steps replacement
        ## 1. Replace the map values in the template with params name
        for key, value in map.items():
            template = template.replace("["+key+"]", value)
        # return template

        ## 2. Replace the params name with the actual values in form fields
        # Keys with flag
        pattern_flag = r'-(.) \$(\w+)'
        template = re.sub(pattern_flag, lambda match: replace_flag(match, params), template)

        # Keys with no flag
        pattern_no_flag = r'\$(\w+)'
        template = re.sub(pattern_no_flag, lambda match: replace_no_flag(match, params), template)

        return template
        
    def generate_script(self, params):
        if self.enviroment is None:
            return "No enviroment selected"
        else:
            template = self.fetch_template("templates/" + self.enviroment + ".txt")
            self.script = self.custom_replace(template, self.map, params)
            return self.script


def main():
    parser = argparse.ArgumentParser(description = "Engine")

    # argument for params dictionary
    parser.add_argument("-p", "--params", type = str, help = "Params Dictionary")
    args = parser.parse_args()

    if args.params:
        try:
            my_dict = ast.literal_eval(args.my_dict)  # Safely parse the dictionary string
            if isinstance(my_dict, dict):
                print("Parsed dictionary:", my_dict)
            else:
                print("Invalid dictionary format")
        except (SyntaxError, ValueError):
            print("Invalid dictionary format")
    else:
        print("No dictionary provided.")
        parser.print_help()


if __name__ == "__main__":
    main()